app = "g-bot"
primary_region = "fra" # Frankfurt a legalacsonyabb latency Magyarországról

[build]
  dockerfile = "Dockerfile"

[env]
  DATABASE_URL = "sqlite:///data/g-bot.db"

[[mounts]]
  source = "bot_data"
  destination = "/data"
